In [1]:
import numpy as np
import pandas as pd

In [2]:
A=np.random.seed(1)
A = np.random.randint(0, 10 ,[4,4])
A

array([[5, 8, 9, 5],
       [0, 0, 1, 7],
       [6, 9, 2, 4],
       [5, 2, 4, 2]])

In [3]:
def fact(n):
        k=1
        for i in range(k,n+1):
            k=k*i
        print (k)  

fact (3)

6


In [4]:
def fact2(n):
    ans=1
    if n>1:
        ans=ans*fact(n-1)
    return ans

fact(6)

720


In [5]:
A

B = np.where(A > 6, 0, A)
B


array([[5, 0, 0, 5],
       [0, 0, 1, 0],
       [6, 0, 2, 4],
       [5, 2, 4, 2]])

In [10]:
print (A[:,0])
print (A[0])
print (len(A[0]))
print (len(A))

def f(x):
    ligne= len(x)
    col= len(x[0])
    
    t =[]
    for j in range(col):
        l=[]
        for i in range(ligne):
            l.append(x[i][j])
        t.append(l)
    return t
f(A)

[5 0 6 5]
[5 8 9 5]
4
4


[[5, 0, 6, 5], [8, 0, 9, 2], [9, 1, 2, 4], [5, 7, 4, 2]]

In [ ]:
def transpose(matrix):
    rows = len(matrix)
    columns = len(matrix[0])

    matrix_T = []
    for j in range(columns):
        row = []
        for i in range(rows):
            row.append(matrix[i][j])
            matrix_T.append(row)

    return matrix_T

In [ ]:
transpose(A)

In [13]:
grid= np.array([[0, 4, 3, 0, 8, 0, 2, 5, 0],
       [6, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 9, 4],
       [9, 0, 0, 0, 0, 4, 0, 7, 0],
       [0, 0, 0, 6, 0, 8, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 0, 3],
       [8, 2, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5],
       [0, 3, 4, 0, 9, 0, 7, 1, 0]])

print (grid)

def possible(x,y,n):
    global grid
    for i in range(9):
        if grid[i][y]==n:
            return False
    for i in range(9):
        if grid[x][i]==n:
            return False
    return True
        
    x0= (x//3)*3
    y0 =(y//3)*3
    
    for i in range(0,3):
        for j in range(0,3):
            if grid[x0+i][y0+i]==n:
                return False
    return True
                                

def solve(grid):
    for x in range(9) :
        for y in range(9) :  
            if grid[x][y] == 0:
                for n in range(1,10):
                    if possible (x,y,n):
                        grid[x][y]= n
                        solve(grid) 
                        grid[x][y]= 0
                return
    print (grid)  
    
solve(grid)

[[0 4 3 0 8 0 2 5 0]
 [6 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 9 4]
 [9 0 0 0 0 4 0 7 0]
 [0 0 0 6 0 8 0 0 0]
 [0 1 0 2 0 0 0 0 3]
 [8 2 0 5 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 5]
 [0 3 4 0 9 0 7 1 0]]
[[1 4 3 7 8 6 2 5 9]
 [6 5 1 4 2 3 9 8 7]
 [2 7 8 3 5 1 6 9 4]
 [9 6 2 1 3 4 5 7 8]
 [3 9 5 6 7 8 1 4 2]
 [7 1 9 2 4 5 8 6 3]
 [8 2 7 5 6 9 4 3 1]
 [4 8 6 9 1 7 3 2 5]
 [5 3 4 8 9 2 7 1 6]]
[[1 4 3 7 8 6 2 5 9]
 [6 5 1 4 2 3 9 8 7]
 [2 7 8 3 5 1 6 9 4]
 [9 6 2 1 3 4 5 7 8]
 [4 9 5 6 7 8 1 3 2]
 [7 1 9 2 4 5 8 6 3]
 [8 2 7 5 6 9 3 4 1]
 [3 8 6 9 1 7 4 2 5]
 [5 3 4 8 9 2 7 1 6]]
[[1 4 3 7 8 6 2 5 9]
 [6 5 1 4 2 3 9 8 7]
 [2 7 8 3 5 1 6 9 4]
 [9 6 2 1 3 4 5 7 8]
 [4 9 5 6 7 8 1 3 2]
 [7 1 9 2 6 5 8 4 3]
 [8 2 7 5 4 9 3 6 1]
 [3 8 6 9 1 7 4 2 5]
 [5 3 4 8 9 2 7 1 6]]
[[1 4 3 7 8 6 2 5 9]
 [6 5 1 4 2 3 9 8 7]
 [2 7 8 3 5 1 6 9 4]
 [9 6 2 1 3 4 5 7 8]
 [7 9 5 6 1 8 3 4 2]
 [4 1 9 2 7 5 8 6 3]
 [8 2 7 5 6 9 4 3 1]
 [3 8 6 9 4 7 1 2 5]
 [5 3 4 8 9 2 7 1 6]]
[[1 4 3 7 8 6 2 5 9]
 [6 5 1 4 2 3 9 8 7]
 [2 7 8 

KeyboardInterrupt: 

In [13]:
arr=[1,2,3,4,5]
def mult(arr):
    ans=1
    for i in arr:
        ans=i*ans
    return ans
w=mult(arr)
w

120

In [14]:
height=[1,8,6,2,5,4,8,3,7]

In [ ]:

class Solution(object):
    def maxArea(self, height):
        
        vol =0
        left=0
        right=(len(height)-1)
        
        while left<right:
            if height[left]>=height[right]:
                vol=max(height[right]*(right-left),vol)
                right-=1
            else:
                vol=max(height[left]*(right-left),vol)
                left +=1
        return vol

In [ ]:
a=Solution()
a.maxArea(height)

In [ ]:
class Solution(object):
    def twosum(self, nums,target):
        dic=dict()
        for i in range(len(nums)):
            if nums[i] in dic:
                return [dic[nums[i]],i]
        
            else:
                dic[target - nums[i]] = i
                
    def twosum2(self,nums,target):
        nums=enumerate(nums)
        nums=sorted(nums, key=lambda x:x[1])
        
        l=0
        r=len(nums)-1
        
        while l<r:
            if nums[l][1]+nums[r][1]==target:
                return (nums[l][0],nums[r][0])
            elif nums[l][1]+nums[r][1]<target:
                l=l+1
            else:
                r=r-1
                
            
        
nums=[2,7,11,15]
target=9
Solution().twosum(nums,target)

In [ ]:
Solution().twosum2(nums,target)


In [ ]:
options=[6,9,20]
def boite(x):
    if x<0:
        return False
    elif x==0:
        return True
    for i in options:
        if boite(x-i):
            return True
    return False
boite(21)

In [ ]:
class Solution:
    def Roman(self,s):
        dic={'I': 1,'V': 5, 'X': 10,'L': 50,'C': 100,'D': 500, 'M': 1000}
        
        sum = 0
        for i in range(len(s)-1):
            if dic[s[i]]<dic[s[i+1]]:
                sum-=dic[s[i]]
            else:
                sum+=dic[s[i]]
        return sum +dic[s[-1]]
                
        

In [ ]:
s='III'
Solution().Roman(s)

In [ ]:
  dic={'I': 1,'V': 5, 'X': 10,'L': 50,'C': 100,'D': 500, 'M': 1000}
dic[s[-1]]        

In [ ]:
strs=['flower','floor','fla','florere']

class Solution:
    def pref(self,strs):
        
        if not strs:
            return ''
        shortest=min(strs,key=len)
        for i,j in enumerate(shortest):
            for x in strs:
                if x[i]!=j:
                    return shortest[:i]
        return shortest


In [ ]:
Solution().pref(strs)

In [ ]:
class Solution:
    def pascal(self,rows):
        res=[[1]]
        for i in range(1,rows):
            res+=[list(map(lambda x,y :x+y, res[-1]+[0],[0]+res[-1]))]
        return res[:rows]
    
s=Solution().pascal(3)
s

In [ ]:
s="abcdeefgh"
class Solution:
    def length(self, s):
        
        usedcar={}
        start=maxlength=0
        
        
        for i, c in enumerate(s):
            if c in usedcar and start<=usedcar[c]:
                start=usedcar[c]+1
            else:
                maxlength=max(maxlength,i-start+1)
            
            usedcar[c]=i
            
        return maxlength
                            





In [ ]:
Solution().length(s)

In [ ]:
list(enumerate(s))

In [ ]:
alpha='abcdefghijklmnopqrstuvwxyz'
dic={}
for x in range(0,26):
    dic[alpha[x]]=x+1
    
dic

phrase= "plop"
for i in phrase:
    print (dic[i])

In [ ]:
nums = [1,1,2]

In [ ]:
class Solution:
    def removedupli(self,nums):
        x=1
        for i in range (len(nums)-1):
            if (nums[i]!=nums[i+1]):
                nums[x]=nums[i+1]
                x+=1
        return x
        

In [ ]:
Solution().removedupli(nums)

In [ ]:
nums=[5,7,7,8,8,10]
target = 8

In [ ]:
class Solution:
    def searchRange(self, nums, target):
        def search(n):
            lo, hi = 0, len(nums)
            while lo < hi:
                mid = (lo + hi) // 2
                if nums[mid] >= n:
                    hi = mid
                else:
                    lo = mid + 1
            return lo
        lo = search(target)
        return [lo, search(target+1)-1] if target in nums[lo:lo+1] else [-1, -1]

In [ ]:
Solution().searchRange(nums,target)

In [ ]:
class Solution:
    def searchRange(self, nums, target):
        def binarySearchLeft(A, x):
            left, right = 0, len(A) - 1
            while left <= right:
                mid = (left + right) // 2
                if x > A[mid]: left = mid + 1
                else: right = mid - 1
            return left

        def binarySearchRight(A, x):
            left, right = 0, len(A) - 1
            while left <= right:
                mid = (left + right) // 2
                if x >= A[mid]: left = mid + 1
                else: right = mid - 1
            return right

        left, right = binarySearchLeft(nums, target), binarySearchRight(nums, target)
        return (left, right) if left <= right else [-1, -1]

In [ ]:
Solution().searchRange(nums,target)

In [ ]:
prices = [7,1,5,3,6,4]
class Solution:
    def maxprof(self,prices):
        maxprofit=0
        minprice=float('inf')
        for price in prices:
            minprice=min(minprice,price)
            profit=price-minprice
            maxprofit=max(maxprofit,profit)
        return maxprofit
 
    def pricer(self,prices):
        maxprofit=0
        left=0
        right=1
        
        while right<len(prices):
            profit=prices[right]-prices[left]
            if prices[left]<prices[right]:
                maxprofit=max(profit,maxprofit)
            else:
                left=right
            right=right+1
            
        return maxprofit
        
        

In [ ]:
Solution().maxprof(prices)

In [ ]:
Solution().pricer(prices)

In [11]:
class Solution:
    def threeSum(self, nums,):
  
        nums.sort()
        N, result = len(nums), []
        for i in range(N):
            if i > 0 and nums[i] == nums[i-1]:
                continue
            target = nums[i]*-1
            s,e = i+1, N-1
            while s<e:
                if nums[s]+nums[e] == target:
                    result.append([nums[i], nums[s], nums[e]])
                    s = s+1
                if nums[s] == nums[s-1]:
                    s = s+1
                elif nums[s] + nums[e] < target:
                    s = s+1
                else:
                    e = e-1
        return result
    
        

In [12]:
nums=[0,1,-1,2,-2,0,4,-4,6]
Solution().threeSum(nums)

[[-4, -2, 6], [-4, 0, 4], [-2, 0, 2], [-1, 0, 1]]

In [13]:
class Solution:
    def threesum2(self,nums):
        res=set()
        n,p,z =[],[],[]
        for i in nums:
            if i==0:
                z.append(i)
            
            elif i<0:
                n.append(i)
            else:
                p.append(i)
                
        N=set(n)
        P=set(p)
        Z=set(z)
        
        if Z:
            for num in N:
                if -num in P:
                    res.add((-num,0,num))
        if len(Z)>3:
            res.add((0,0,0))
            
        for i in range(len(P)):
            for j in range(i+1,len(P)):
                target=(nums[i]+nums[j])*-1
                if target in N:
                    res.add(tuple(sorted([nums[i],nums[j],target])))
                    
        for i in range(len(N)):
            for j in range(i+1,len(N)):
                target=(nums[i]+nums[j])*-1
                if target in P:
                    res.add(tuple(sorted([nums[i],nums[j],target])))       
        return res
    

In [14]:
nums=[0,1,-1,2,-2,0,4,-4,6]
Solution().threesum2(nums)

{(-2, 0, 2), (-1, -1, 2), (-1, 0, 1), (1, 0, -1), (2, 0, -2), (4, 0, -4)}

In [ ]:
class Solution:
    def maxprod(self,nums):
        
        ans=nums[0]
        maxprod=nums[0]
        minprod=nums[0]
        
        for i in range(1,len(nums)):
            x=max(nums[i],maxprod*nums[i],minprod*nums[i])
            y=min(nums[i],maxprod*nums[i],minprod*nums[i])
            maxprod=x
            minprod=y   
            ans=max(maxprod,ans)
        return ans
        
        

In [ ]:
nums=[1,3,4,2,6]
Solution().maxprod(nums)

In [ ]:
class Solution:
    def parenth(self,strs):
        dic={"[":"]",'(':')','{':'}'}
        stack=[]
        
        for x in strs:
            if x in dic:
                stack.append(x)
            elif len(stack)==0 or dic[stack.pop()]!=x:
                return False
        return len(stack)==0
        

In [ ]:
strs='([()])'

Solution().parenth(strs)

In [ ]:
nums =  [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
class Solution:
    def rotate(self,matrix):
        r=len(matrix)-1
        l=0
        
        while l<r:
            matrix[l], matrix[r]= matrix[r], matrix[l]
            l=l+1
            r=r-1
        
        for i in range(len(matrix)):
            for j in range(i):
                matrix[i][j], matrix[j][i]= matrix[j][i], matrix[i][j]        
        
        
        
        return matrix

In [ ]:
Solution().rotate(nums)       